-- weather_embeddings.sql
-- Table to store text chunk embeddings for semantic search using pgvector
-- Requires: CREATE EXTENSION vector;

-- Enable pgvector extension (run this first)
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS weather_embeddings (
    -- Primary key
    id BIGSERIAL PRIMARY KEY,
    
    -- Foreign key to weather_documents
    document_id TEXT NOT NULL,
    
    -- Chunk information
    chunk_index INTEGER NOT NULL,     -- Position of chunk in document (0-based)
    chunk_text TEXT NOT NULL,         -- The actual text chunk (800 chars with 100 overlap)
    
    -- Vector embedding (384 dimensions for all-MiniLM-L6-v2)
    embedding vector(384) NOT NULL,   -- pgvector type
    
    -- Metadata
    model_name TEXT DEFAULT 'sentence-transformers/all-MiniLM-L6-v2',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign key constraint
    CONSTRAINT fk_document 
        FOREIGN KEY (document_id) 
        REFERENCES weather_documents(id) 
        ON DELETE CASCADE,
    
    -- Unique constraint to prevent duplicate chunks
    CONSTRAINT unique_document_chunk 
        UNIQUE (document_id, chunk_index)
);

-- HNSW index for fast approximate nearest neighbor search
-- Using cosine distance (<=>) operator
CREATE INDEX IF NOT EXISTS idx_weather_embeddings_hnsw 
    ON weather_embeddings 
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- Alternative: IVFFlat index (another ANN algorithm)
-- Uncomment if you prefer IVFFlat over HNSW
-- CREATE INDEX idx_weather_embeddings_ivfflat 
--     ON weather_embeddings 
--     USING ivfflat (embedding vector_cosine_ops)
--     WITH (lists = 100);

-- Index on document_id for joining back to source documents
CREATE INDEX IF NOT EXISTS idx_weather_embeddings_document_id 
    ON weather_embeddings(document_id);

-- Index on created_at for time-based queries
CREATE INDEX IF NOT EXISTS idx_weather_embeddings_created_at 
    ON weather_embeddings(created_at DESC);

-- Comments for documentation
COMMENT ON TABLE weather_embeddings IS 
    'Stores vector embeddings of weather document text chunks for semantic search';

COMMENT ON COLUMN weather_embeddings.embedding IS 
    'Vector embedding (384-dim) generated by sentence-transformers/all-MiniLM-L6-v2';

COMMENT ON COLUMN weather_embeddings.chunk_text IS 
    'Text chunk (max 800 chars with 100 char overlap between chunks)';

COMMENT ON INDEX idx_weather_embeddings_hnsw IS 
    'HNSW index for fast cosine similarity search on embeddings';

-- Example semantic search query:
-- 
-- WITH query_embedding AS (
--     SELECT embedding FROM weather_embeddings LIMIT 1  -- Replace with actual query embedding
-- )
-- SELECT 
--     e.chunk_text,
--     d.headline,
--     d.location,
--     d.source_type,
--     e.embedding <=> (SELECT embedding FROM query_embedding) AS distance
-- FROM weather_embeddings e
-- JOIN weather_documents d ON e.document_id = d.id
-- ORDER BY e.embedding <=> (SELECT embedding FROM query_embedding)
-- LIMIT 10;
